### ISSUE TITLE
flow-decision-engine 

### ISSUE THREAD

**Issue by hpl002** [stacc/stacc-flow-community#12]
/deploy and /validate endpoints are not prefixed with _stacc-cloud_

Expected /stacc-cloud/deploy but got /deploy

Not a big deal, but we should have a clear convention on this. E.g: flow-process and api-gw uses this prefix

**Comment by Anders-eide-stacc** [comment]
This has been fixed in the upcoming v4.0 release, alongside a lot of other minor fixes as well as many new features.

The current changelog listing the upcoming changes can be found here: 
[https://flow-docs.stacc.dev/framework/flow-decision-engine/4.0/Changelog](https://flow-docs.stacc.dev/framework/flow-decision-engine/4.0/Changelog)
