### ISSUE TITLE
Case Manager: feature (synchronize versioning of components with process version)

### ISSUE THREAD

**Issue by hpl002** [stacc/stacc-flow-community#8]
**Relevant Flow module(s)**
Case Manager  

**What do you want to accomplish? Please describe.**
Synchronize versioning of components with process version.

Issue came up when we were deploying some new component changes that only affected the latest process version.
These were deployed while not accounting for any and all preexisting flows(big mistake).. 

This naturally caused some nasty breakage when deployed to a environment with lots of old processes as these data structures were not accounted for.

Another case being if one wishes to add additional functionality, but only have this available for the latest process version. This new functionality is not relevant for any previous process versions and should therefore not be rendered.

**Describe the suggested solution**
Would be neat if one could somehow map a relationship between the versioning of components and process version. The case manger could then render the correct component version. _This way we have have old components for old flows and new components for new flows._ :) 

Current fix being to use expose process version to component and use conditional rendering or bump/drop existing flows so that these do not break the component.
 

**Additional context**
Issue briefly mentioned during a team meeting and the cause for some slight headaches last week..

**Comment by Anders-eide-stacc** [comment]
Hmm, unfortunately we do not have any suitable mechanisms today for implementing this kind of synchronization.

While we do have the `flow._meta.processVersion`-field, it should be noted that this is field is auto-incremented field by the process engine whenever a new version of the process diagram is deployed, and thus can vary between environments.

At least for now, I think the best way to handle this issue is to always keep backwards compatability in mind to prevent older flows from crashing. Then, if introducing new features that should only be enabled for newer flows, gate these behind feature flags on flow state, or the task's context.

**Comment by hpl002** [comment]
feel free to close if this is not prioritized @Anders-eide-stacc

**Comment by Karolined** [comment]
Not prioritized on short term
